// project/src/App.vue
<template>
  <HelloWorld/>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'


export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
@font-face {
    font-family: "72";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/72-Regular-full.woff") format("woff");
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: "72";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/72-Bold-full.woff") format("woff");
    font-weight: 700;
    font-style: normal;
}

@font-face {
    font-family: "72";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/72-Light-full.woff") format("woff");
    font-weight: 300;
    font-style: normal;
}

@font-face {
    font-family: "SAP-icons";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/sap_horizon/fonts/SAP-icons.woff") format("woff");
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'BusinessSuiteInAppSymbols';
    src: url('~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/BusinessSuiteInAppSymbols.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'SAP-icons-TNT';
    src: url('~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/SAP-icons-TNT.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

html {
    font-size: 16px;
}
</style>

// to_do_fundstyles/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'to_do_fundstyles';
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  #app {
    margin-top: 10%;
    margin-left: 25%;
    width:50%;

    
  }

  @font-face {
    font-family: "72";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/72-Bold-full.woff") format("woff");
    font-weight: 700;
    font-style: normal;
}

@font-face {
    font-family: "72";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/72-Light-full.woff") format("woff");
    font-weight: 300;
    font-style: normal;
}

@font-face {
    font-family: "SAP-icons";
    src: url("~@sap-theming/theming-base-content/content/Base/baseLib/sap_horizon/fonts/SAP-icons.woff") format("woff");
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'BusinessSuiteInAppSymbols';
    src: url('~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/BusinessSuiteInAppSymbols.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'SAP-icons-TNT';
    src: url('~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/SAP-icons-TNT.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

html {
    font-size: 16px;

}
 
</style>

<div id="app">
  
    <header class="fd-page__header">
      <div class="fd-action-bar">
        <div class="fd-action-bar__header">
          <h3 class="fd-action-bar__title">To-Do</h3>
        </div>
        <p class="fd-action-bar__description">Prepare shopping list</p>
      </div>
    </header>
    <div class="fd-page__content">
      <section class="fd-section">
        <div class="fd-panel">
          <div class="fd-panel__body">
            <form class="fd-has-margin-bottom-xs" >
              <div class="fd-form-item">
                <div class="fd-input-group">
                  <input class="fd-input fd-input-group__input" type="text" placeholder="Add new todo item"
                          maxlength="280">
                  <span class="fd-input-group__addon fd-input-group__addon--button">
                <button type="submit" class="fd-input-group__button fd-button fd-button--light" >
                  Add
                </button>
              </span>
                </div>
              </div>
            </form>

            <button class="fd-button fd-has-margin-bottom-xs" >Uncheck all</button>

            <ul class="fd-list">
              <li class="fd-list__item">
                <div class="fd-form-item todo-label">
                  <input type="checkbox"   class="fd-checkbox fd-has-margin-right-medium"
                >
                  <label class="fd-checkbox__label" >
                    <span class="fd-list__title">Eggs</span>
                  </label>
                </div>

                <button class="fd-button" type="button" ><span class="sap-icon--delete"></span>
                </button>
              </li>
              <li class="fd-list__item">
                <div class="fd-form-item todo-label">
                  <input type="checkbox"   class="fd-checkbox fd-has-margin-right-medium"
                >
                  <label class="fd-checkbox__label" >
                    <span class="fd-list__title">Salad</span>
                  </label>
                </div>

                <button class="fd-button" type="button" ><span class="sap-icon--delete"></span>
                </button>
              </li>
            </ul>
          </div>
        </div>
      </section>

    </div>

</div>

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
